### ISSUE TITLE
Reject a new point if it is too close to an already accepted point

### ISSUE THREAD

**Issue by rfung-uwm-edu** [lbl-camera/HGDL#20]
In hgdl/local_methods/local_optimizer.py

In lines# 55-58, a minimum is rejected if it is too close to another minimum.

As-is, if a minimum with a higher index (i) is too close to a minimum with a lower index (j, j<i), j is rejected. That is, a previously accepted point is rejected to accommodate a new point.

You probably want to reject i instead. That is, you want to reject a new point if it is too close to an already accepted point.

I suggest changing line# 58 from “local_success[j] = False” to “local_success[i] = False”.

Thanks.
Russell Fung (University of Wisconsin Milwaukee)

**Comment by rfung-uwm-edu** [comment]
In hgdl/global_methods/global_optimizer.py, genetic_step method:

As-is, dads’ weight is the same as moms’ weight.

Suggested change:

line# 67 should be changed to weighted_linear_sum = weights[0].reshape(-1,1)*X[moms] + weights[1].reshape(-1,1)*X[dads]

Thanks. 
Russell Fung (University of Wisconsin Milwaukee)

**Comment by MarcusMNoack** [comment]
Thanks for this comment. We will look into it as soon as possible.

**Comment by MarcusMNoack** [comment]
Thanks again for this comment. The changes have been made and are available starting with version 2.1.4
