### ISSUE TITLE
Moms & Dads have the same weights in genetic_step method

### ISSUE THREAD

**Issue by rfung-uwm-edu** [lbl-camera/HGDL#21]
In hgdl/global_methods/global_optimizer.py, genetic_step method:

As-is, dads’ weight is the same as moms’ weight.

Suggested change:

line# 67 should be changed to weighted_linear_sum = weights[0].reshape(-1,1)*X[moms] + weights[1].reshape(-1,1)*X[dads]

Thanks. 
Russell Fung (University of Wisconsin Milwaukee)

**Comment by MarcusMNoack** [comment]
Thank you for this suggestion. We will include it in the next update.

**Comment by MarcusMNoack** [comment]
Thanks again for this comment. The changes have been made and are available starting with version 2.1.4
